volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: girday/kittygram_backend:latest
    env_file: .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/app/collected_static
      - media:/app/media

  frontend:
    image: girday/kittygram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: girday/kittygram_gateway:latest
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media
